# .github/workflows/sync.yml
# https://stackoverflow.com/questions/23793062/can-forks-be-synced-automatically-in-github

name: Merge upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '10,20,30,40,50 * * * *'
  push:
    paths-ignore:
      - .github/workflows/bintray.yml
      - .github/workflows/cui.yml
      - .github/workflows/doc.yml
      - .github/workflows/main.yml
      - .github/workflows/shadow.yml
      - .github/workflows/sync.yml
      - .github/workflows/sync.yml
      - .github/workflows/build.yml
      - .github/workflows/*.yml
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'foxes1998'
          git config --global user.email 'foxes1998@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/mamoe/mirai.git
          git fetch upstream

          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          git checkout -b dev origin/dev
          git merge --no-edit upstream/dev
          git push origin dev

          git checkout master
          git merge --no-edit upstream/master
          git push origin master

          # etc
